"""
Classical-CV pseudo-ground-truth mask generation — ported from Unet_Extraction.ipynb.

IMPORTANT: These masks are PSEUDO-GROUND-TRUTH generated by classical computer
vision (Sobel gradients + morphology). They are NOT human annotations.
They were used to train the U-Net in lieu of a manually labelled dataset.
"""
from pathlib import Path
import cv2
import numpy as np


def directional_gradient(img: np.ndarray) -> np.ndarray:
    """
    Compute a multi-directional gradient magnitude image and normalise to uint8.

    Sobel x/y -> diagonal approximations -> max of all four magnitudes.
    Source: Unet_Extraction.ipynb — ported verbatim.
    """
    sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
    sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)
    diag1 = (sobelx + sobely) / 2
    diag2 = (sobelx - sobely) / 2
    G = np.maximum(
        np.maximum(np.abs(sobelx), np.abs(sobely)),
        np.maximum(np.abs(diag1), np.abs(diag2)),
    )
    G = cv2.normalize(G, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    return G


def lower_boundary_mask(img_gray: np.ndarray) -> np.ndarray:
    """
    Build a lower-boundary mask from a gradient image.

    Pixels >= 90th-percentile gradient -> 255; apply MORPH_OPEN with 3x3 kernel.
    Source: Unet_Extraction.ipynb — ported verbatim.
    """
    G = directional_gradient(img_gray)
    threshold = np.percentile(G, 90)
    mask = np.where(G >= threshold, 255, 0).astype(np.uint8)
    kernel = np.ones((3, 3), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    return mask


def upper_boundary_mask(
    lower_mask: np.ndarray,
    img_gray: np.ndarray,
) -> np.ndarray:
    """
    Build an upper-boundary mask relative to the lower boundary.

    For each column: find the row of the first bright maximum in img_gray that
    lies ABOVE the lowest nonzero row in lower_mask.  Dilate result with (1,3).
    Source: Unet_Extraction.ipynb — ported verbatim.
    """
    h, w = img_gray.shape
    upper_mask = np.zeros((h, w), dtype=np.uint8)

    for col in range(w):
        lower_col = lower_mask[:, col]
        nonzero_rows = np.nonzero(lower_col)[0]
        if len(nonzero_rows) == 0:
            continue
        lower_boundary_row = nonzero_rows[-1]  # lowest nonzero in column

        # Find the brightest pixel above the lower boundary
        col_pixels = img_gray[:lower_boundary_row, col]
        if col_pixels.size == 0:
            continue
        upper_row = int(np.argmax(col_pixels))
        upper_mask[upper_row, col] = 255

    kernel = np.ones((1, 3), np.uint8)
    upper_mask = cv2.dilate(upper_mask, kernel)
    return upper_mask


def create_final_mask(img_path: str) -> np.ndarray:
    """
    Combine lower + upper boundary masks into a single pseudo-ground-truth mask.

    Reads the image as grayscale, builds both masks, and returns their union.
    Source: Unet_Extraction.ipynb — ported verbatim.

    NOTE: result is NOT a human annotation; see module docstring.
    """
    img_gray = cv2.imread(str(img_path), cv2.IMREAD_GRAYSCALE)
    if img_gray is None:
        raise FileNotFoundError(f"Cannot read image: {img_path}")
    lower = lower_boundary_mask(img_gray)
    upper = upper_boundary_mask(lower, img_gray)
    final_mask = cv2.bitwise_or(lower, upper)
    return final_mask


def column_fill(mask: np.ndarray) -> np.ndarray:
    """
    Fill each column from first nonzero pixel to last nonzero pixel with 255.

    Source: Unet_Extraction.ipynb — ported verbatim.
    """
    filled = mask.copy()
    h = filled.shape[0]
    for col in range(filled.shape[1]):
        col_data = filled[:, col]
        nonzero = np.nonzero(col_data)[0]
        if len(nonzero) >= 2:
            filled[nonzero[0]:nonzero[-1] + 1, col] = 255
    return filled


def extract_bone_region(
    img: np.ndarray,
    mask: np.ndarray,
    size: int = 100,
) -> np.ndarray:
    """
    Apply mask to image via bitwise_and and resize to (size, size).

    Source: Unet_Extraction.ipynb — ported verbatim.
    """
    bone = cv2.bitwise_and(img, img, mask=mask)
    bone_resized = cv2.resize(bone, (size, size))
    return bone_resized
